steps:
  # Шаг 1: Сборка Docker-образа
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/bookbot', '.']

  # Шаг 2: Публикация Docker-образа в Google Artifact Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/bookbot']

  # Шаг 3: Деплой в Google Cloud Run
  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      - 'run'
      - 'deploy'
      - 'pocketbook-bot'
      - '--image'
      - 'gcr.io/$PROJECT_ID/bookbot'
      - '--region'
      - 'europe-central2'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'

images:
  - 'gcr.io/$PROJECT_ID/bookbot'
