# Cloud Build configuration for building and deploying the bookbot project.

steps:
# Step 1: Clone the repository with all Git metadata, including tags.
- name: 'gcr.io/cloud-builders/git'
  entrypoint: 'bash'
  args:
  - '-c'
  - |
    # Clone the repository to the build workspace
    git clone https://github.com/aashavskiy/aliksbookbot.git /workspace
    cd /workspace

    # Check out the main branch (ensure it's the default branch)
    git checkout main

# Step 2: Build the Docker image.
- name: 'gcr.io/cloud-builders/docker'
  args:
  - 'build'
  - '-t'
  - 'gcr.io/$PROJECT_ID/bookbot' # Tag the Docker image with the project ID
  - '.'
  env:
  - 'DEFAULT_VERSION=$(git describe --tags || echo "unknown")' # Pass the version as an environment variable

# Step 3: Push the Docker image to Google Container Registry.
images:
- 'gcr.io/$PROJECT_ID/bookbot'

# Step 4 (Optional): Deploy directly to Cloud Run (if auto-deployment is configured).
# Uncomment the following section to deploy automatically:
- name: 'gcr.io/cloud-builders/gcloud'
  args:
   - 'run'
   - 'deploy'
   - 'pocketbook-bot'
   - '--image'
   - 'gcr.io/$PROJECT_ID/bookbot'
   - '--region'
   - 'europe-central2'
   - '--platform'
   - 'managed'
   - '--allow-unauthenticated'
